// <auto-generated />
namespace ProjetoIntranet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changes_3009 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes_3009));
        
        string IMigrationMetadata.Id
        {
            get { return "201509301505569_changes_30-09"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
